import { useQuery } from '@tanstack/react-query';import { Bar, BarChart, ResponsiveContainer, XAxis, YAxis } from 'recharts';import { api, ApiResponse } from '../lib/api';import { Button, Card, Empty } from '../components/ui';
const chart=[{name:'Jan',rent:82000},{name:'Feb',rent:96000},{name:'Mar',rent:112000},{name:'Apr',rent:128000},{name:'May',rent:156000}];
export function OwnerDashboard(){const q=useQuery({queryKey:['ownerDashboard'],queryFn:async()=> (await api.get<ApiResponse<Record<string,unknown>>>('/dashboard/owner')).data.data});return <div className="space-y-6"><h1 className="text-4xl font-black">Owner Dashboard</h1><div className="grid gap-4 md:grid-cols-4">{['totalProperties','totalTenants','pendingRents','monthlyRevenue'].map(k=><Card key={k}><p className="text-sm text-slate-500">{k}</p><p className="text-3xl font-black">{String(q.data?.[k]??'—')}</p></Card>)}</div><Card><h2 className="text-2xl font-bold">Payment analytics</h2><ResponsiveContainer width="100%" height={280}><BarChart data={chart}><XAxis dataKey="name"/><YAxis/><Bar dataKey="rent" fill="#7c3aed" radius={[8,8,0,0]}/></BarChart></ResponsiveContainer></Card></div>}
export function TenantDashboard(){const q=useQuery({queryKey:['tenantDashboard'],queryFn:async()=> (await api.get<ApiResponse<Record<string,unknown>>>('/dashboard/tenant')).data.data});return <div className="space-y-6"><h1 className="text-4xl font-black">Tenant Dashboard</h1><div className="grid gap-4 md:grid-cols-3"><Card><p>Status</p><p className="text-3xl font-black text-leaf">{String(q.data?.status??'CURRENT')}</p></Card><Card><p>Next due</p><p className="text-3xl font-black">{String(q.data?.nextDueInDays??7)} days</p></Card><Card><p>Pending</p><p className="text-3xl font-black">₹{String(q.data?.pendingAmount??0)}</p></Card></div><Card><h2 className="text-2xl font-bold">Quick payment</h2><p className="my-3 text-slate-500">Pay rent, advance, EB, water, or maintenance securely.</p><Button>Pay now</Button></Card></div>}
export function AdminDashboard(){return <div className="space-y-6"><h1 className="text-4xl font-black">Admin Panel</h1><div className="grid gap-4 md:grid-cols-3"><Card>Manage users</Card><Card>Manage properties</Card><Card>Subscriptions & complaints</Card></div></div>}
export function Properties(){return <div className="space-y-6"><h1 className="text-4xl font-black">Properties</h1><Card><Button>Add property</Button><div className="mt-6"><Empty title="No properties loaded yet. Add your first rental unit."/></div></Card></div>}
export function Tenants(){return <div className="space-y-6"><h1 className="text-4xl font-black">Tenants</h1><Card><Button>Invite tenant</Button><div className="mt-6"><Empty title="Tenant KYC, agreements, and assignments will appear here."/></div></Card></div>}
export function Payments(){return <div className="space-y-6"><h1 className="text-4xl font-black">Payments & Invoices</h1><Card><Button>Create Razorpay order</Button><div className="mt-6"><Empty title="Payment history with receipt downloads will appear here."/></div></Card></div>}
export function Notifications(){return <div className="space-y-6"><h1 className="text-4xl font-black">Notifications</h1><Card><Empty title="Rent reminders, agreement alerts, and payment updates appear here."/></Card></div>}
export function Settings(){return <div className="space-y-6"><h1 className="text-4xl font-black">Profile & Settings</h1><Card><p>Update profile, upload ID proof, change password, and configure reminders.</p></Card></div>}
